import "./css/Impressum.css";
import { FooterLink } from "./FooterStyles";

export default function Impressum() {
  return (
    <>
      <div className="impressum">
        <h3>IMPRESSUM ANGABEN GEMÄSS § 5 TMG</h3>
        <FooterLink href="https://www.facebook.com/raumvier2020/">
          <i className="fab fa-youtube">
            <span
              style={{
                marginLeft: "10px",
              }}
            >
              Facebook
            </span>
          </i>
        </FooterLink>
        <FooterLink href="https://www.instagram.com/raumvier/">
          <i className="fab fa-facebook-f">
            <span
              style={{
                marginLeft: "10px",
              }}
            >
              Instagram
            </span>
          </i>
        </FooterLink>
        <br />
        <br />
        <p>Julian Voss, Raumvier Events </p>
        <p>Liegnitzerstr.34, 10999 Berlin</p>
        <p>VAT: DE356318538</p>
        <p>ST.N.: 14/574/04300</p>
        <br />

        <h3>DISCLAIMER</h3>

        <h4> HAFTUNG FÜR INHALTE</h4>

        <p>
          ALS DIENSTEANBIETER SIND WIR GEMÄSS § 7 ABS.1 TMG FÜR EIGENE INHALTE
          AUF DIESEN SEITEN NACH DEN ALLGEMEINEN GESETZEN VERANTWORTLICH. NACH
          §§ 8 BIS 10 TMG SIND WIR ALS DIENSTEANBIETER JEDOCH NICHT
          VERPFLICHTET, ÜBERMITTELTE ODER GESPEICHERTE FREMDE INFORMATIONEN ZU
          ÜBERWACHEN ODER NACH UMSTÄNDEN ZU FORSCHEN, DIE AUF EINE RECHTSWIDRIGE
          TÄTIGKEIT HINWEISEN.
          <br />
          <br /> VERPFLICHTUNGEN ZUR ENTFERNUNG ODER SPERRUNG DER NUTZUNG VON
          INFORMATIONEN NACH DEN ALLGEMEINEN GESETZEN BLEIBEN HIERVON UNBERÜHRT.
          EINE DIESBEZÜGLICHE HAFTUNG IST JEDOCH ERST AB DEM ZEITPUNKT DER
          KENNTNIS EINER KONKRETEN RECHTSVERLETZUNG MÖGLICH. BEI BEKANNTWERDEN
          VON ENTSPRECHENDEN RECHTSVERLETZUNGEN WERDEN WIR DIESE INHALTE
          UMGEHEND ENTFERNEN.
          <br />
          <br />
        </p>
        <h4> HAFTUNG FÜR LINKS</h4>

        <p>
          UNSER ANGEBOT ENTHÄLT LINKS ZU EXTERNEN WEBSITES DRITTER, AUF DEREN
          INHALTE WIR KEINEN EINFLUSS HABEN. DESHALB KÖNNEN WIR FÜR DIESE
          FREMDEN INHALTE AUCH KEINE GEWÄHR ÜBERNEHMEN. FÜR DIE INHALTE DER
          VERLINKTEN SEITEN IST STETS DER JEWEILIGE ANBIETER ODER BETREIBER DER
          SEITEN VERANTWORTLICH. DIE VERLINKTEN SEITEN WURDEN ZUM ZEITPUNKT DER
          VERLINKUNG AUF MÖGLICHE RECHTSVERSTÖSSE ÜBERPRÜFT. RECHTSWIDRIGE
          INHALTE WAREN ZUM ZEITPUNKT DER VERLINKUNG NICHT ERKENNBAR.
          <br />
          <br /> EINE PERMANENTE INHALTLICHE KONTROLLE DER VERLINKTEN SEITEN IST
          JEDOCH OHNE KONKRETE ANHALTSPUNKTE EINER RECHTSVERLETZUNG NICHT
          ZUMUTBAR. BEI BEKANNTWERDEN VON RECHTSVERLETZUNGEN WERDEN WIR
          DERARTIGE LINKS UMGEHEND ENTFERNEN.
          <br />
          <br />
        </p>
        <h4>URHEBERRECHT</h4>

        <p>
          DIE DURCH DIE SEITENBETREIBER ERSTELLTEN INHALTE UND WERKE AUF DIESEN
          SEITEN UNTERLIEGEN DEM DEUTSCHEN URHEBERRECHT. DIE VERVIELFÄLTIGUNG,
          BEARBEITUNG, VERBREITUNG UND JEDE ART DER VERWERTUNG AUSSERHALB DER
          GRENZEN DES URHEBERRECHTES BEDÜRFEN DER SCHRIFTLICHEN ZUSTIMMUNG DES
          JEWEILIGEN AUTORS BZW. ERSTELLERS. DOWNLOADS UND KOPIEN DIESER SEITE
          SIND NUR FÜR DEN PRIVATEN, NICHT KOMMERZIELLEN GEBRAUCH GESTATTET.
          <br />
          <br />
          SOWEIT DIE INHALTE AUF DIESER SEITE NICHT VOM BETREIBER ERSTELLT
          WURDEN, WERDEN DIE URHEBERRECHTE DRITTER BEACHTET. INSBESONDERE WERDEN
          INHALTE DRITTER ALS SOLCHE GEKENNZEICHNET. SOLLTEN SIE TROTZDEM AUF
          EINE URHEBERRECHTSVERLETZUNG AUFMERKSAM WERDEN, BITTEN WIR UM EINEN
          ENTSPRECHENDEN HINWEIS. BEI BEKANNTWERDEN VON RECHTSVERLETZUNGEN
          WERDEN WIR DERARTIGE INHALTE UMGEHEND ENTFERNEN.
        </p>
        <br />
        <h3> Copyright © 2023 </h3>
      </div>
    </>
  );
}
